steps:
  # -------------------------
  # Build Frontend
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend'
    args:
      [
        'build',
        '-t',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend:latest',
        './frontend'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend'
    args:
      [
        'push',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend:latest'
      ]

  # -------------------------
  # Build Backend
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args:
      [
        'build',
        '-t',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend:latest',
        './backend'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args:
      [
        'push',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend:latest'
      ]

  # -------------------------
  # Restart Backend Deployment
  # -------------------------
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Restart Backend Deployment'
    args: ['rollout','restart','deployment/backend','-n','prod']

  # -------------------------
  # Restart Frontend Deployment
  # -------------------------
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Restart Frontend Deployment'
    args: ['rollout','restart','deployment/frontend','-n','prod']

options:
  logging: "CLOUD_LOGGING_ONLY"

# Список образов, которые будут зарегистрированы в Cloud Build
images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend:latest'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend:latest'